/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;


import java.sql.Connection;

import CW2Group4.DB;
import CW2Group4.InsertTable;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.*;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.data.jdbc.JDBCCategoryDataset;
/**
 *
 * @author Saitama
 * 
 */
public class Dashboard extends javax.swing.JFrame {
    
    HashMap<Integer, String> pie = new HashMap<>();
    public String countries;
    public static String getUsername;
     ChartFrame frame;
    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        showFundingTable();
        showDataTable();
        showOrgTable();
        showProjectsTable();
        showOrgActivityTable();
        drawBar();
        
        
    }
    
    public Dashboard(String username){
        initComponents();
        showFundingTable();
        showDataTable();
        showOrgTable();
        showProjectsTable();
        showOrgActivityTable();
        drawBar();
        getUsername = username;
        
        user.setText(getUsername);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        MainPanel = new javax.swing.JPanel();
        home = new javax.swing.JPanel();
        fundingScheme = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        chartPanel = new javax.swing.JPanel();
        orgActivityType = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        data = new javax.swing.JPanel();
        projectPanel = new javax.swing.JPanel();
        projectScrollPane = new javax.swing.JScrollPane();
        projectTable = new javax.swing.JTable();
        searchProjects = new javax.swing.JLabel();
        projectComboBox = new javax.swing.JComboBox<>();
        projectTextField = new javax.swing.JTextField();
        createProject = new javax.swing.JButton();
        deleteProject = new javax.swing.JButton();
        amendProject = new javax.swing.JButton();
        proSearch = new javax.swing.JButton();
        projectDeleteTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        orgPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        searchOrg = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        orgComboBox = new javax.swing.JComboBox<>();
        orgSearch = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        organisationDeleteTextField = new javax.swing.JTextField();
        dataPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        dataComboBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        searchData = new javax.swing.JTextField();
        createData = new javax.swing.JButton();
        amendData = new javax.swing.JButton();
        dataDelete = new javax.swing.JButton();
        dataSearch = new javax.swing.JButton();
        deleteDataTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        TopPanel = new javax.swing.JPanel();
        welcomeLabel = new javax.swing.JLabel();
        Guest = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        toggleButton = new javax.swing.JButton();
        Quit = new javax.swing.JButton();
        user = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 836, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainPanel.setLayout(new java.awt.CardLayout());

        fundingScheme.setBorder(javax.swing.BorderFactory.createTitledBorder("Funding Scheme Categories"));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Code", "Title", "Language"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout fundingSchemeLayout = new javax.swing.GroupLayout(fundingScheme);
        fundingScheme.setLayout(fundingSchemeLayout);
        fundingSchemeLayout.setHorizontalGroup(
            fundingSchemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fundingSchemeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        fundingSchemeLayout.setVerticalGroup(
            fundingSchemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fundingSchemeLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout chartPanelLayout = new javax.swing.GroupLayout(chartPanel);
        chartPanel.setLayout(chartPanelLayout);
        chartPanelLayout.setHorizontalGroup(
            chartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 743, Short.MAX_VALUE)
        );
        chartPanelLayout.setVerticalGroup(
            chartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        orgActivityType.setBorder(javax.swing.BorderFactory.createTitledBorder("Organisation Activity Types"));

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Code", "Title", "Language"
            }
        ));
        jScrollPane4.setViewportView(jTable5);

        javax.swing.GroupLayout orgActivityTypeLayout = new javax.swing.GroupLayout(orgActivityType);
        orgActivityType.setLayout(orgActivityTypeLayout);
        orgActivityTypeLayout.setHorizontalGroup(
            orgActivityTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, orgActivityTypeLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        orgActivityTypeLayout.setVerticalGroup(
            orgActivityTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orgActivityTypeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout homeLayout = new javax.swing.GroupLayout(home);
        home.setLayout(homeLayout);
        homeLayout.setHorizontalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeLayout.createSequentialGroup()
                .addComponent(fundingScheme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chartPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(orgActivityType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        homeLayout.setVerticalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeLayout.createSequentialGroup()
                .addGroup(homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chartPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(homeLayout.createSequentialGroup()
                        .addComponent(fundingScheme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 32, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(homeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(orgActivityType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        MainPanel.add(home, "card3");

        projectPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Projects"));

        projectTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        projectScrollPane.setViewportView(projectTable);

        searchProjects.setText("Search Projects");

        projectComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Show All", "By ID", "By RCN", "By Acronym", "By Status", "By Programme", "By Topics", "By Start Date", "By End Date" }));
        projectComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectComboBoxActionPerformed(evt);
            }
        });

        createProject.setText("Create");
        createProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createProjectActionPerformed(evt);
            }
        });

        deleteProject.setText("Delete");
        deleteProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteProjectActionPerformed(evt);
            }
        });

        amendProject.setText("Amend");
        amendProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amendProjectActionPerformed(evt);
            }
        });

        proSearch.setText("Search");
        proSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proSearchActionPerformed(evt);
            }
        });

        jLabel5.setText("Project ID: ");

        javax.swing.GroupLayout projectPanelLayout = new javax.swing.GroupLayout(projectPanel);
        projectPanel.setLayout(projectPanelLayout);
        projectPanelLayout.setHorizontalGroup(
            projectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(projectPanelLayout.createSequentialGroup()
                .addComponent(projectScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(projectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(projectPanelLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(projectDeleteTextField))
                    .addComponent(projectTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, projectPanelLayout.createSequentialGroup()
                        .addComponent(searchProjects)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(projectComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, projectPanelLayout.createSequentialGroup()
                        .addGroup(projectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(projectPanelLayout.createSequentialGroup()
                                .addComponent(createProject)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(amendProject))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, projectPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(deleteProject)
                                .addGap(1, 1, 1)))
                        .addGap(37, 37, 37)
                        .addComponent(proSearch)))
                .addContainerGap())
        );
        projectPanelLayout.setVerticalGroup(
            projectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(projectScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(projectPanelLayout.createSequentialGroup()
                .addGroup(projectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchProjects)
                    .addComponent(projectComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(projectTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(projectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createProject)
                    .addComponent(proSearch)
                    .addComponent(amendProject))
                .addGap(26, 26, 26)
                .addGroup(projectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(projectDeleteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(deleteProject)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        orgPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Organisations"));

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable4);

        jLabel4.setText("Search Organisations");

        jButton5.setText("Create");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton7.setText("Amend");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Delete");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        orgComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Show All", "Project ID", "Project RCN", "Organisation ID", "Name", "Short Name", "Activity Type", "EC Contribution", "End Participation" }));

        orgSearch.setText("Search");
        orgSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orgSearchActionPerformed(evt);
            }
        });

        jLabel2.setText("Organisation ID: ");

        organisationDeleteTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                organisationDeleteTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout orgPanelLayout = new javax.swing.GroupLayout(orgPanel);
        orgPanel.setLayout(orgPanelLayout);
        orgPanelLayout.setHorizontalGroup(
            orgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orgPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(orgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(orgPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(orgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, orgPanelLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(orgComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(orgPanelLayout.createSequentialGroup()
                                .addGroup(orgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(searchOrg, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(orgPanelLayout.createSequentialGroup()
                                        .addComponent(jButton5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton7)
                                        .addGap(32, 32, 32)
                                        .addComponent(orgSearch)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(orgPanelLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(organisationDeleteTextField)))
                        .addContainerGap())
                    .addGroup(orgPanelLayout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jButton8)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        orgPanelLayout.setVerticalGroup(
            orgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(orgPanelLayout.createSequentialGroup()
                .addGroup(orgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(orgComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchOrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(orgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(orgSearch)
                    .addComponent(jButton7))
                .addGap(24, 24, 24)
                .addGroup(orgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(organisationDeleteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton8)
                .addGap(0, 19, Short.MAX_VALUE))
        );

        dataPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Cordis 2020 Data"));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable3);

        dataComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Show All", "By ID", "By Project RCN", "By Acronym", "By Name", "By Project ID", "By Short Name", "By EC Contribution" }));
        dataComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataComboBoxActionPerformed(evt);
            }
        });

        jLabel3.setText("Search Dataset");

        searchData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchDataActionPerformed(evt);
            }
        });

        createData.setText("Create");
        createData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createDataActionPerformed(evt);
            }
        });

        amendData.setText("Amend");
        amendData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amendDataActionPerformed(evt);
            }
        });

        dataDelete.setText("Delete");
        dataDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataDeleteActionPerformed(evt);
            }
        });

        dataSearch.setText("Search");
        dataSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataSearchActionPerformed(evt);
            }
        });

        jLabel1.setText("Organisation ID: ");

        javax.swing.GroupLayout dataPanelLayout = new javax.swing.GroupLayout(dataPanel);
        dataPanel.setLayout(dataPanelLayout);
        dataPanelLayout.setHorizontalGroup(
            dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dataPanelLayout.createSequentialGroup()
                        .addComponent(createData)
                        .addGap(31, 31, 31)
                        .addComponent(amendData)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dataSearch))
                    .addGroup(dataPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dataComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dataPanelLayout.createSequentialGroup()
                        .addGroup(dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchData, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(dataPanelLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(dataPanelLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(dataDelete))
                                    .addComponent(deleteDataTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        dataPanelLayout.setVerticalGroup(
            dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(dataPanelLayout.createSequentialGroup()
                .addGroup(dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createData)
                    .addComponent(dataSearch)
                    .addComponent(amendData))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteDataTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dataDelete)
                .addContainerGap())
        );

        javax.swing.GroupLayout dataLayout = new javax.swing.GroupLayout(data);
        data.setLayout(dataLayout);
        dataLayout.setHorizontalGroup(
            dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(projectPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(orgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dataPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        dataLayout.setVerticalGroup(
            dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dataPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(orgPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(projectPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
        );

        MainPanel.add(data, "card3");

        TopPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        welcomeLabel.setText("Welcome to Cordis2020 Dashboard");

        Guest.setText("You are logged in as:");

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dashboard/logo.png"))); // NOI18N

        toggleButton.setText("Switch View");
        toggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleButtonActionPerformed(evt);
            }
        });

        Quit.setText("Quit");
        Quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TopPanelLayout = new javax.swing.GroupLayout(TopPanel);
        TopPanel.setLayout(TopPanelLayout);
        TopPanelLayout.setHorizontalGroup(
            TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(Logo)
                .addGap(87, 87, 87)
                .addComponent(toggleButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(welcomeLabel)
                    .addGroup(TopPanelLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(Guest)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(user)))
                .addGap(104, 104, 104))
            .addGroup(TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(TopPanelLayout.createSequentialGroup()
                    .addGap(401, 401, 401)
                    .addComponent(Quit)
                    .addContainerGap(401, Short.MAX_VALUE)))
        );
        TopPanelLayout.setVerticalGroup(
            TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Logo)
                    .addGroup(TopPanelLayout.createSequentialGroup()
                        .addComponent(welcomeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Guest)
                            .addComponent(toggleButton)
                            .addComponent(user))))
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(TopPanelLayout.createSequentialGroup()
                    .addGap(37, 37, 37)
                    .addComponent(Quit)
                    .addContainerGap(38, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TopPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(TopPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void toggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleButtonActionPerformed
        CardLayout cl = (CardLayout)(MainPanel.getLayout());
        cl.next(MainPanel);
        System.out.println("Switch View Button clicked");
    }//GEN-LAST:event_toggleButtonActionPerformed

    private void createDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createDataActionPerformed
        // TODO add your handling code here:
        System.out.println("Create button pressed.");
        Create create = new Create();
        create.setVisible(true);
        
       
        
        
        
       
                    
        
        
    }//GEN-LAST:event_createDataActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        System.out.println("Create Org Button clicked!");
        createOrganisation createOrganisation = new createOrganisation();
        createOrganisation.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void createProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createProjectActionPerformed
        // TODO add your handling code here:
        System.out.println("Create Project Button clicked!");
        createProject createProject = new createProject();
        createProject.setVisible(true);
 
    }//GEN-LAST:event_createProjectActionPerformed

    private void dataComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataComboBoxActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_dataComboBoxActionPerformed

    private void searchDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchDataActionPerformed
        // TODO add your handling code here:
       
        
        
        
        
        
        
    }//GEN-LAST:event_searchDataActionPerformed

    private void projectComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectComboBoxActionPerformed
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_projectComboBoxActionPerformed

    private void dataSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataSearchActionPerformed
        // TODO add your handling code here:
        String sql = "";
        
        int ch = dataComboBox.getSelectedIndex();
        
        switch(ch){
            case 0: 
            sql = "SELECT * from dataset";
                DisplayData(sql);
                break;

            case 1:  
            sql = "SELECT * from dataset WHERE dataId=\""+searchData.getText()+"\"";
                DisplayData(sql);
                System.out.println("Printing " + sql);
                break;
                
            case 2: 
            sql = "SELECT * from dataset WHERE proRcn=\""+searchData.getText()+"\"";
                DisplayData(sql);
                break;
            
            case 3: 
            sql = "SELECT * from dataset WHERE proAcronym=\""+searchData.getText()+"\"";
                DisplayData(sql);
                break;
                
            case 4: 
            sql = "SELECT * from dataset WHERE orgName=\""+searchData.getText()+"\"";
                DisplayData(sql);
                break;
                
            case 5: 
            sql = "SELECT * from dataset WHERE proId=\""+searchData.getText()+"\"";
                DisplayData(sql);
                break;
                
            case 6: 
            sql = "SELECT * from dataset WHERE orgSname=\""+searchData.getText()+"\"";
                DisplayData(sql);
                break;
            
            case 7: 
            sql = "SELECT * from dataset WHERE orgEcCont=\""+searchData.getText()+"\"";
                DisplayData(sql);
                break;
           
        }
        
        
        
        
    }//GEN-LAST:event_dataSearchActionPerformed

    private void proSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proSearchActionPerformed
        // TODO add your handling code here:
        String sql = "";
        
        int ch = projectComboBox.getSelectedIndex();
        
        switch(ch){
            case 0: 
            sql = "SELECT * from projects";
                DisplayProject(sql);
                break;

            case 1:  
            sql = "SELECT * from projects WHERE proId=\""+projectTextField.getText()+"\"";
                DisplayProject(sql);
                System.out.println("Printing " + sql);
                break;
                
            case 2:  
            sql = "SELECT * from projects WHERE proRcn=\""+projectTextField.getText()+"\"";
                DisplayProject(sql);
                System.out.println("Printing " + sql);
                break;
            case 3:  
            sql = "SELECT * from projects WHERE proAcronym=\""+projectTextField.getText()+"\"";
                DisplayProject(sql);
                System.out.println("Printing " + sql);
                break;
            case 4: 
            sql = "SELECT * from projects WHERE proStatus=\""+projectTextField.getText()+"\"";
                DisplayProject(sql);
                break;
                
            case 5: 
            sql = "SELECT * from projects WHERE proProgramme=\""+projectTextField.getText()+"\"";
                DisplayProject(sql);
                break;
                
            case 6: 
            sql = "SELECT * from projects WHERE proTopics=\""+projectTextField.getText()+"\"";
                DisplayProject(sql);
                break;
            
            case 7: 
            sql = "SELECT * from projects WHERE proStartDate=\""+projectTextField.getText()+"\"";
                DisplayProject(sql);
                break;
                
            case 8: 
            sql = "SELECT * from projects WHERE proEndDate=\""+projectTextField.getText()+"\"";
                DisplayProject(sql);
                break;
                
        }
    }//GEN-LAST:event_proSearchActionPerformed

    private void orgSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orgSearchActionPerformed
        // TODO add your handling code here:
        String sql = "";
        
        int ch = orgComboBox.getSelectedIndex();
        
        switch(ch){
            case 0: 
            sql = "SELECT * from organisations";
                DisplayOrg(sql);
                break;
            
            case 1:  
            sql = "SELECT * from organisations WHERE proId=\""+searchOrg.getText()+"\"";
                DisplayOrg(sql);
                System.out.println("Printing " + sql);
                break;
                
            case 2:  
            sql = "SELECT * from organisations WHERE proRcn=\""+searchOrg.getText()+"\"";
                DisplayOrg(sql);
                System.out.println("Printing " + sql);
                break;
                
            case 3:  
            sql = "SELECT * from organisations WHERE orgId=\""+searchOrg.getText()+"\"";
                DisplayOrg(sql);
                System.out.println("Printing " + sql);
                break;
                
            case 4:  
            sql = "SELECT * from organisations WHERE orgName=\""+searchOrg.getText()+"\"";
                DisplayOrg(sql);
                System.out.println("Printing " + sql);
                break;
            
            case 5:  
            sql = "SELECT * from organisations WHERE orgSname=\""+searchOrg.getText()+"\"";
                DisplayOrg(sql);
                System.out.println("Printing " + sql);
                break;
                
            case 6:  
            sql = "SELECT * from organisations WHERE orgActivityType=\""+searchOrg.getText()+"\"";
                DisplayOrg(sql);
                System.out.println("Printing " + sql);
                break;
                
            case 7:  
            sql = "SELECT * from organisations WHERE orgEcCont=\""+searchOrg.getText()+"\"";
                DisplayOrg(sql);
                System.out.println("Printing " + sql);
                break;
                
            case 8:  
            sql = "SELECT * from organisations WHERE orgEndPart=\""+searchOrg.getText()+"\"";
                DisplayOrg(sql);
                System.out.println("Printing " + sql);
                break;
            
            
        }
    }//GEN-LAST:event_orgSearchActionPerformed

    private void QuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuitActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_QuitActionPerformed

    private void dataDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataDeleteActionPerformed
        // TODO add your handling code here:
        
        int id = Integer.parseInt(deleteDataTextField.getText());
        
        InsertTable.deleteDataset(id);
        
        JOptionPane.showMessageDialog(this, "Project: " + id + " deleted." );
        
       
        
    }//GEN-LAST:event_dataDeleteActionPerformed

    private void organisationDeleteTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_organisationDeleteTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_organisationDeleteTextFieldActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(organisationDeleteTextField.getText());
        
        InsertTable.deleteOrganisation(id);
        
        JOptionPane.showMessageDialog(this, "Organisation: " + id + " deleted." );
        
    }//GEN-LAST:event_jButton8ActionPerformed

    private void deleteProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteProjectActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(projectDeleteTextField.getText());
        
        InsertTable.deleteProject(id);
        
        JOptionPane.showMessageDialog(this, "Project: " + id + " deleted." );
        
       
    }//GEN-LAST:event_deleteProjectActionPerformed

    private void amendDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amendDataActionPerformed
        // TODO add your handling code here:
        System.out.println("Amend Data button pressed.");
        amendData amend = new amendData();
        amend.setVisible(true);
    }//GEN-LAST:event_amendDataActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        System.out.println("Amend Org button pressed.");
        amendOrganisation amend = new amendOrganisation();
        amend.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void amendProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amendProjectActionPerformed
        // TODO add your handling code here:
        System.out.println("Amend Project button pressed.");
        amendProject amend = new amendProject();
        amend.setVisible(true);
    }//GEN-LAST:event_amendProjectActionPerformed

    public void showFundingTable(){
        System.out.println("Show All Button clicked!");
        
        Connection con = DB.getConnection();
        
        Statement stmt = null;
        ResultSet rs = null;
        
       
        
        
        try{
             //get columns
             
             stmt = con.createStatement();
             
             rs = stmt.executeQuery("SELECT * from fundingScheme");
        
        ResultSetMetaData rsmd = rs.getMetaData();
        int columnCount = rsmd.getColumnCount();
        
        DefaultTableModel df = (DefaultTableModel) jTable1.getModel();
        
        df.setColumnCount(0);
        
        for(int i =1; i<=columnCount; i++){
            df.addColumn(rsmd.getColumnName(i));
        }
        
        df.setRowCount(0);
        
        while(rs.next()){
            String[] a = new String[columnCount];
            for(int i=0; i<columnCount; i++){
                a[i] = rs.getString(i+1);
            }
            
            df.addRow(a);
        }
        df.fireTableDataChanged();
        
        rs.close();
        
            
        } catch(Exception e){
            System.out.println("Error in showing data" + e.getMessage());
        }
    }
    
    public void showOrgActivityTable(){
        System.out.println("Show All Button clicked!");
        
        Connection con = DB.getConnection();
        
        Statement stmt = null;
        ResultSet rs = null;
        
       
        
        
        try{
             //get columns
             
             stmt = con.createStatement();
             
             rs = stmt.executeQuery("SELECT * from activityType");
        
        ResultSetMetaData rsmd = rs.getMetaData();
        int columnCount = rsmd.getColumnCount();
        
        DefaultTableModel df = (DefaultTableModel) jTable5.getModel();
        
        df.setColumnCount(0);
        
        for(int i =1; i<=columnCount; i++){
            df.addColumn(rsmd.getColumnName(i));
        }
        
        df.setRowCount(0);
        
        while(rs.next()){
            String[] a = new String[columnCount];
            for(int i=0; i<columnCount; i++){
                a[i] = rs.getString(i+1);
            }
            
            df.addRow(a);
        }
        df.fireTableDataChanged();
        
        rs.close();
        
            
        } catch(Exception e){
            System.out.println("Error in showing data" + e.getMessage());
        }
    }
    
    public void showDataTable(){
        System.out.println("Show All Button clicked!");
        
        Connection con = DB.getConnection();
        
        Statement stmt = null;
        ResultSet rs = null;
        
       
        
        
        try{
             //get columns
             
             stmt = con.createStatement();
             
             rs = stmt.executeQuery("SELECT * from dataset");
        
        ResultSetMetaData rsmd = rs.getMetaData();
        int columnCount = rsmd.getColumnCount();
        
        DefaultTableModel df = (DefaultTableModel) jTable3.getModel();
        
        df.setColumnCount(0);
        
        for(int i =1; i<=columnCount; i++){
            
            df.addColumn(rsmd.getColumnName(i));
        }
        
        df.setRowCount(0);
        
        while(rs.next()){
            String[] a = new String[columnCount];
            for(int i=0; i<columnCount; i++){
                a[i] = rs.getString(i+1);
            }
            
            df.addRow(a);
        }
        df.fireTableDataChanged();
        
        rs.close();
        
            
        } catch(Exception e){
            System.out.println("Error in showing data" + e.getMessage());
        }
    }
    
    public void showOrgTable(){
        System.out.println("Show All Button clicked!");
        
        Connection con = DB.getConnection();
        
        Statement stmt = null;
        ResultSet rs = null;
        
       
        
        
        try{
             //get columns
             
             stmt = con.createStatement();
             
             rs = stmt.executeQuery("SELECT * from organisations");
        
        ResultSetMetaData rsmd = rs.getMetaData();
        int columnCount = rsmd.getColumnCount();
        
        DefaultTableModel df = (DefaultTableModel) jTable4.getModel();
        
        df.setColumnCount(0);
        
        for(int i =1; i<=columnCount; i++){
            if(i<=13 ){
            df.addColumn(rsmd.getColumnName(i));
            }
        }
        
        df.setRowCount(0);
        
        while(rs.next()){
            String[] a = new String[columnCount];
            for(int i=0; i<columnCount; i++){
                if(i<=13 ){
                a[i] = rs.getString(i+1);
                }
            }
            
            df.addRow(a);
        }
        df.fireTableDataChanged();
        
        rs.close();
        
            
        } catch(Exception e){
            System.out.println("Error in showing data" + e.getMessage());
        }
    }
    
    public void showProjectsTable(){
        System.out.println("Show All Button clicked!");
        
        Connection con = DB.getConnection();
        
        Statement stmt = null;
        ResultSet rs = null;
        
       
        
        
        try{
             //get columns
             
             stmt = con.createStatement();
             
             rs = stmt.executeQuery("SELECT * from projects");
        
        ResultSetMetaData rsmd = rs.getMetaData();
        int columnCount = rsmd.getColumnCount();
        
        DefaultTableModel df = (DefaultTableModel) projectTable.getModel();
        
        df.setColumnCount(0);
        
        for(int i =1; i<=columnCount; i++){
            if(i<=17 ){
            df.addColumn(rsmd.getColumnName(i));
            }
        }
        
        df.setRowCount(0);
        
        while(rs.next()){
            String[] a = new String[columnCount];
            for(int i=0; i<columnCount; i++){
                if(i<=17 ){
                a[i] = rs.getString(i+1);
                }
            }
            
            df.addRow(a);
        }
        df.fireTableDataChanged();
        
        rs.close();
        
            
        } catch(Exception e){
            System.out.println("Error in showing data" + e.getMessage());
        }
    }
    /**
     * @param args the command line arguments
     */
   public static void main(String args[]) {
        
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
        
        
     
        
    }
        
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Guest;
    private javax.swing.JLabel Logo;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JButton Quit;
    private javax.swing.JPanel TopPanel;
    private javax.swing.JButton amendData;
    private javax.swing.JButton amendProject;
    private javax.swing.JPanel chartPanel;
    private javax.swing.JButton createData;
    private javax.swing.JButton createProject;
    private javax.swing.JPanel data;
    private javax.swing.JComboBox<String> dataComboBox;
    private javax.swing.JButton dataDelete;
    private javax.swing.JPanel dataPanel;
    private javax.swing.JButton dataSearch;
    private javax.swing.JTextField deleteDataTextField;
    private javax.swing.JButton deleteProject;
    private javax.swing.JPanel fundingScheme;
    private javax.swing.JPanel home;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JPanel orgActivityType;
    private javax.swing.JComboBox<String> orgComboBox;
    private javax.swing.JPanel orgPanel;
    private javax.swing.JButton orgSearch;
    private javax.swing.JTextField organisationDeleteTextField;
    private javax.swing.JButton proSearch;
    private javax.swing.JComboBox<String> projectComboBox;
    private javax.swing.JTextField projectDeleteTextField;
    private javax.swing.JPanel projectPanel;
    private javax.swing.JScrollPane projectScrollPane;
    private javax.swing.JTable projectTable;
    private javax.swing.JTextField projectTextField;
    private javax.swing.JTextField searchData;
    private javax.swing.JTextField searchOrg;
    private javax.swing.JLabel searchProjects;
    private javax.swing.JButton toggleButton;
    private javax.swing.JLabel user;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables

    private void DisplayData(String sql) {
        try{
            Connection con = DB.getConnection();
            
            try(Statement stmt = con.createStatement()){
                ResultSet rs = stmt.executeQuery(sql);
                
                ResultSetMetaData rsmd = rs.getMetaData();
                int columnCount = rsmd.getColumnCount();
                
                DefaultTableModel tm = (DefaultTableModel) jTable3.getModel();
                
                tm.setColumnCount(0);
                
                for(int i =1; i<= columnCount; i++){
                    tm.addColumn(rsmd.getColumnName(i));
                }
                
                tm.setRowCount(0);
                
                while(rs.next()){
                    String[] a = new String[columnCount];
                    for(int i=0; i<columnCount; i++){
                        a[i] = rs.getString(i+1);
                    }
                    
                    tm.addRow(a);
                }
                
                tm.fireTableDataChanged();
                rs.close();
                
            }
        } catch(SQLException ex){
            System.out.println("Error displaying Data SQL Query" + ex.getMessage());
        }
    }
    
    private void DisplayProject(String sql) {
        try{
            Connection con = DB.getConnection();
            
            try(Statement stmt = con.createStatement()){
                ResultSet rs = stmt.executeQuery(sql);
                
                ResultSetMetaData rsmd = rs.getMetaData();
                int columnCount = rsmd.getColumnCount();
                
                DefaultTableModel tm = (DefaultTableModel) projectTable.getModel();
                
                tm.setColumnCount(0);
                
                for(int i =1; i<= columnCount; i++){
                    tm.addColumn(rsmd.getColumnName(i));
                }
                
                tm.setRowCount(0);
                
                while(rs.next()){
                    String[] a = new String[columnCount];
                    for(int i=0; i<columnCount; i++){
                        a[i] = rs.getString(i+1);
                    }
                    
                    tm.addRow(a);
                }
                
                tm.fireTableDataChanged();
                rs.close();
                
            }
        } catch(SQLException ex){
            System.out.println("Error displaying Project SQL Query" + ex.getMessage());
        }
    }

    private void DisplayOrg(String sql) {
        try{
            Connection con = DB.getConnection();
            
            try(Statement stmt = con.createStatement()){
                ResultSet rs = stmt.executeQuery(sql);
                
                ResultSetMetaData rsmd = rs.getMetaData();
                int columnCount = rsmd.getColumnCount();
                
                DefaultTableModel tm = (DefaultTableModel) jTable4.getModel();
                
                tm.setColumnCount(0);
                
                for(int i =1; i<= columnCount; i++){
                    tm.addColumn(rsmd.getColumnName(i));
                }
                
                tm.setRowCount(0);
                
                while(rs.next()){
                    String[] a = new String[columnCount];
                    for(int i=0; i<columnCount; i++){
                        a[i] = rs.getString(i+1);
                    }
                    
                    tm.addRow(a);
                }
                
                tm.fireTableDataChanged();
                rs.close();
                
            }
        } catch(SQLException ex){
            System.out.println("Error displaying Organisation SQL Query" + ex.getMessage());
        }
    }
    
     public void drawBar() {
        Connection con = DB.getConnection();
        Statement stmt = null;
        JDBCCategoryDataset dataset = null;

       
        try {

            stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("Select * from organisations limit 6");
            
            int n = 0;
            while (rs.next()) {
                int numColumns = rs.getMetaData().getColumnCount();
                n++;
                for (int i = 1; i <= numColumns; i++) {
                    System.out.print(" " + rs.getObject(i));
                }

                System.out.println("");
            }

            rs.close();
            

            String sql = "SELECT orgActivityType, count(*) As Number_Of FROM organisations GROUP BY orgActivityType ";

            dataset = new JDBCCategoryDataset(con, sql);

            System.out.println("dataset cols and rows : " + dataset.getColumnCount() + "  " + dataset.getRowCount());
            
        } catch (SQLException ex) {
            System.err.println("SQLException: " + ex.getMessage());
        } finally {
            if (stmt != null) {
                try {
                    stmt.close();
                } catch (SQLException e) {
                    System.err.println("SQLException: " + e.getMessage());
                }
            }
            if (con != null) {
                try {
                    con.close();
                } catch (SQLException e) {
                    System.err.println("SQLException: " + e.getMessage());
                }
            }
        }
        JFreeChart chart = ChartFactory.createBarChart("Organisations by Activity Type",
                "Activity Type", "Number ", dataset, PlotOrientation.VERTICAL, false, true, false);
        chart.setBackgroundPaint(Color.white);
        chart.getTitle().setPaint(Color.blue);

        CategoryPlot p = chart.getCategoryPlot();
        p.setRangeGridlinePaint(Color.blue);
        BarRenderer renderer = (BarRenderer) p.getRenderer();
        renderer.setDrawBarOutline(true);
        renderer.setShadowVisible(true);
        renderer.setItemMargin(-4);
        renderer.setSeriesPaint(0, Color.blue);

        chartPanel.setLayout(new java.awt.BorderLayout());
        
        ChartPanel CP = new ChartPanel(chart);
        
        chartPanel.add(CP, BorderLayout.CENTER);
        
        chartPanel.validate();
        /**frame = new ChartFrame("Organisations by Activity Type", chart);
        frame.setVisible(true);
        frame.setSize(400, 350);*/
       

    }

}


