/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import LoginRegister.UserTable;
import CW2Group4.DB;
import LoginRegister.ProtectUserPassword;
import LoginRegister.VerifyProvidedPassword;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;



/**
 *
 * @author Saitama
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    
    private static String UserName;
    private static String UserPwd;
    private static String UserEmail;
    private static String UserSalt;
    private static String UserGenPwd;

    public static String getUserName() {
        return UserName;
    }

    public static String getUserPwd() {
        return UserPwd;
    }    
    
    public static String getUserEmail() {
        return UserEmail;
    }  
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        Register = new javax.swing.JPanel();
        register = new javax.swing.JButton();
        uemail = new javax.swing.JTextField();
        userEmail = new javax.swing.JLabel();
        userName2 = new javax.swing.JLabel();
        uname2 = new javax.swing.JTextField();
        userPwd2 = new javax.swing.JLabel();
        backToLogin = new javax.swing.JButton();
        upwd2 = new javax.swing.JPasswordField();
        Login = new javax.swing.JPanel();
        uemail1 = new javax.swing.JTextField();
        userEmail1 = new javax.swing.JLabel();
        login = new javax.swing.JButton();
        userPwd = new javax.swing.JLabel();
        Register2 = new javax.swing.JButton();
        upwd = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainPanel.setLayout(new java.awt.CardLayout());

        register.setText("Register");
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });

        uemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uemailActionPerformed(evt);
            }
        });

        userEmail.setText("Email");

        userName2.setText("Username");

        uname2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uname2ActionPerformed(evt);
            }
        });

        userPwd2.setText("Password");

        backToLogin.setText("Login");
        backToLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RegisterLayout = new javax.swing.GroupLayout(Register);
        Register.setLayout(RegisterLayout);
        RegisterLayout.setHorizontalGroup(
            RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterLayout.createSequentialGroup()
                .addGroup(RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegisterLayout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(userPwd2))
                    .addGroup(RegisterLayout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(userName2))
                    .addGroup(RegisterLayout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(register))
                    .addGroup(RegisterLayout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(userEmail))
                    .addGroup(RegisterLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backToLogin))
                    .addGroup(RegisterLayout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(uemail, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                            .addComponent(uname2)
                            .addComponent(upwd2))))
                .addContainerGap(128, Short.MAX_VALUE))
        );
        RegisterLayout.setVerticalGroup(
            RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegisterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backToLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(userName2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(uname2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(userPwd2)
                .addGap(18, 18, 18)
                .addComponent(upwd2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(userEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(uemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(register)
                .addGap(132, 132, 132))
        );

        MainPanel.add(Register, "card2");

        uemail1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uemail1ActionPerformed(evt);
            }
        });

        userEmail1.setText("Email");

        login.setText("Login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });

        userPwd.setText("Password");

        Register2.setText("Sign Up");
        Register2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Register2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LoginLayout = new javax.swing.GroupLayout(Login);
        Login.setLayout(LoginLayout);
        LoginLayout.setHorizontalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginLayout.createSequentialGroup()
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginLayout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(userPwd))
                    .addGroup(LoginLayout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(userEmail1))
                    .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, LoginLayout.createSequentialGroup()
                            .addGap(111, 111, 111)
                            .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(upwd, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(uemail1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, LoginLayout.createSequentialGroup()
                            .addGap(129, 129, 129)
                            .addComponent(login)
                            .addGap(18, 18, 18)
                            .addComponent(Register2))))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        LoginLayout.setVerticalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginLayout.createSequentialGroup()
                .addContainerGap(173, Short.MAX_VALUE)
                .addComponent(userEmail1)
                .addGap(18, 18, 18)
                .addComponent(uemail1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(userPwd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(upwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(login)
                    .addComponent(Register2))
                .addGap(118, 118, 118))
        );

        MainPanel.add(Login, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void uemail1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uemail1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uemail1ActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
        
        Connection con = DB.getConnected();
        UserEmail = uemail1.getText();
        UserPwd = new String(upwd.getText());
        try {
            Statement stmt = con.createStatement();
            String sql = "SELECT * FROM User WHERE userEmail = '" + UserEmail + "'";
            
            ResultSet rs = stmt.executeQuery(sql);
           
            while(rs.next()){
                // Encrypted and Base64 encoded password read from database
                UserName = rs.getString(1);
                
            }
            
            
            
            rs.close();
        } catch (SQLException ex) {
            Logger.getLogger(VerifyProvidedPassword.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        String emailRegex = "^(.+)@(.+)$";
        
        
        if(!UserEmail.matches(emailRegex)){
            JOptionPane.showMessageDialog(this, "Email is not in a valid format");
            return;
        }
        
        if(UserEmail.equals("")|| UserPwd.equals("")){
                    JOptionPane.showMessageDialog(this, "Please fill in the required fields");
                } 
        
             if(VerifyProvidedPassword.VerifyProvidedPassword(UserEmail, UserPwd)){
                 
                    
                    JOptionPane.showMessageDialog(this, "Login successful.");
                    
                    Dashboard dashboard = new Dashboard(UserName);
                    dashboard.setVisible(true);
                    this.setVisible(false);
                    this.dispose();
                
             } else {
                 JOptionPane.showMessageDialog(this, "Password is incorrect");
             }
                
            
                
                
            
       
        
        
    }//GEN-LAST:event_loginActionPerformed
         
    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        // TODO add your handling code here:
        UserName = uname2.getText();
        UserPwd = new String(upwd2.getText());
        UserEmail = uemail.getText();
        
        if(UserName.equals("")|| UserPwd.equals("")||UserEmail.equals("")){
            JOptionPane.showMessageDialog(this, "Please fill out all fields");
            return;
        }
        
        String emailRegex = "^(.+)@(.+)$";
        
        
        if(!UserEmail.matches(emailRegex)){
            JOptionPane.showMessageDialog(this, "Email is not in a valid format");
            return;
        }
        
        /**if(!UserPwd.matches(pwordRegex)){
            JOptionPane.showMessageDialog(this, "Password must have: "
                    + "- 2 uppercase letters"
                    + "- 8 letters"
                    + "- One special character (!@#&*)"
                   
                    + "");
            return;
        }**/
        
        ResultSet userResultSet =  UserTable.get(UserEmail);
        
        List<String> list = ProtectUserPassword.ProtectUserPassword(UserPwd);
        UserSalt = list.get(0);
        UserGenPwd = list.get(1);
        
        
        
        try{
            if(userResultSet.next()){
                JOptionPane.showMessageDialog(this, "User with this email is already registered.");
            } else{
                UserTable.insert(UserName, UserGenPwd, UserEmail, UserSalt);
                JOptionPane.showMessageDialog(this, "User registered.");
            }
        } catch(Exception e){
            System.out.println("Error inserting user" + e.getMessage());
        }
        
        CardLayout cl = (CardLayout)(MainPanel.getLayout());
        cl.next(MainPanel);
        System.out.println("Register button clicked");
    }//GEN-LAST:event_registerActionPerformed

    private void uemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uemailActionPerformed

    private void uname2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uname2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uname2ActionPerformed

    private void Register2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Register2ActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout)(MainPanel.getLayout());
        cl.next(MainPanel);
        System.out.println("Back to Login button clicked");
    }//GEN-LAST:event_Register2ActionPerformed

    private void backToLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToLoginActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout)(MainPanel.getLayout());
        cl.next(MainPanel);
        System.out.println("Back to Login button clicked");
    }//GEN-LAST:event_backToLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    /**public static void main(String args[]) {
     
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Login;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel Register;
    private javax.swing.JButton Register2;
    private javax.swing.JButton backToLogin;
    private javax.swing.JButton login;
    private javax.swing.JButton register;
    private javax.swing.JTextField uemail;
    private javax.swing.JTextField uemail1;
    private javax.swing.JTextField uname2;
    private javax.swing.JPasswordField upwd;
    private javax.swing.JPasswordField upwd2;
    private javax.swing.JLabel userEmail;
    private javax.swing.JLabel userEmail1;
    private javax.swing.JLabel userName2;
    private javax.swing.JLabel userPwd;
    private javax.swing.JLabel userPwd2;
    // End of variables declaration//GEN-END:variables
}
